<?php

$title = 'Novo Usuário';
$this->headTitle($title);

?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
     
<?php
$form->setAttribute('action', $this->url('usuario/default', 
        array('controller'=>'index','action' => 'insert')));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?php echo $this->formRow( $form->get('nome')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow( $form->get('login')); ?>
</div>


<div class="form-group">
    <?php echo $this->formRow( $form->get('email')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow( $form->get('senha')); 
    ?>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->formRow($form->get('submit')); ?>
    </div>
</div>
    
    
    <?php
echo $this->form()->closeTag();

?>
