<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Clientes';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('cliente/default',
             array('controller'=>'index','action'=>'insert'));?>">Novo</a>
 </p>

 
 <table class="table">
 <tr>
     <th>Documento</th>
     <th>Nome</th>
     <th>E-Mail</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($albums as $album) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($album->getDocumento());?></td>
     <td><?php echo $this->escapeHtml($album->getDescricao());?></td>
     <td><?php echo $this->escapeHtml($album->getEmail());?></td>
     <td>
         <a href="<?php echo $this->url('cliente/default',
             array('controller'=>'index','action'=>'edit', 'id' => $album->getClicod()));?>">Edit</a>
         <a href="<?php echo $this->url('cliente/default',
             array('controller'=>'index','action'=>'delete', 'id' => $album->getClicod()));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>