<?php
 // module/Album/view/album/album/index.phtml:

 $title = 'Clientes';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('cliente/default',
             array('controller'=>'index','action'=>'insert'));?>">Novo</a>
 </p>
<a class="btn btn-success" title="Novo"><span class="glyphicon glyphicon-plus"></span></a>
<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Documento</th>
                <th>Nome</th>
                <th>E-Mail</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($albums as $album) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($album->getDocumento());?></td>
                <td><?php echo $this->escapeHtml($album->getDescricao());?></td>
                <td><?php echo $this->escapeHtml($album->getEmail());?></td>
                <td>
                    <a class="btn btn-xs btn-warning" title="Editar" href="<?php echo $this->url('cliente/default',
                        array('controller'=>'index','action'=>'edit', 'id' => $album->getClicod()));?>">
                        <span class="glyphicon glyphicon-pencil"></span></a>
                    <a class="btn btn-xs btn-danger" title="Deletar" 
                       href="<?php echo $this->url('cliente/default',
                        array('controller'=>'index','action'=>'delete', 'id' => $album->getClicod()));?>"><span class="glyphicon glyphicon-remove"></span></a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>