<?php

$title = 'Novo Cliente';
$this->headTitle($title);

?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
     
<?php
$form->setAttribute('action', $this->url('cliente/default', 
        array('controller'=>'index','action' => 'insert')));
$form->prepare();

echo $this->form()->openTag($form);
?>



<div class="form-group">
    <div class="input-group">

        <?= $this->formRow( $form->get('dtcadastro')); ?>

        <div class="row">
            <div class="radio">
                <?php echo $this->formRow( $form->get('tipo')); ?>
            </div>
        </div>


        <div class="row">
            <div class="col-lg-4">
                <?= $this->formRow( $form->get('documento')); ?>
            </div>
        </div>

        <div class="row">   
            <div class="col-md-8">
                <?= $this->formRow( $form->get('descricao')); ?>
            </div>                
            <div class="col-md-4">
                <?= $this->formRow($form->get('email'));?>
            </div>                
        </div> 

        <div class="row">   
            <div class="col-md-2">
                <?= $this->formRow( $form->get('ddd1')); ?>
            </div>                
            <div class="col-md-4">
                <?= $this->formRow($form->get('telefone1'));?>
            </div>                
        </div> 
        
        <div class="row">   
            <div class="col-md-2">
                <?= $this->formRow( $form->get('ddd2')); ?>
            </div>                
            <div class="col-md-4">
                <?= $this->formRow($form->get('telefone2'));?>
            </div>                
        </div> 
        
        <h3>Endereço <small>(Necessário quando houver frete)</small> </h3>

        <div class="row">   
            <div class="col-md-4">
                <?= $this->formRow( $form->get('logradouro')); ?>
            </div>                
            <div class="col-md-4">
                <?= $this->formRow($form->get('numero'));?>
            </div>                
            <div class="col-md-4">
                <?= $this->formRow($form->get('complemento'));?>
            </div>                
        </div> 
        
        <div class="row">   
            <div class="col-md-4">
                <?= $this->formRow( $form->get('bairro')); ?>
            </div>                
            <div class="col-md-4">
                <?= $this->formRow($form->get('cidade'));?>
            </div>                
            <div class="col-md-4">
                <?= $this->formRow($form->get('uf'));?>
            </div>                
        </div> 
        <div class="row">   
            <?= $this->formRow( $form->get('cep')); ?>
        </div> 

        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->formRow($form->get('submit')); ?>
        </div>

    </div> <!-- Input group -->
</div> <!-- Form group -->
    
    <?= $this->form()->closeTag(); ?>
