<?php

$title = 'Novo Cliente';
$this->headTitle($title);

?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
     
<?php
$form->setAttribute('action', $this->url('cliente/default', 
        array('controller'=>'index','action' => 'insert')));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?php echo $this->formRow( $form->get('dtcadastro')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow( $form->get('tipo')); ?>
</div>


<div class="form-group">
    <?php echo $this->formRow( $form->get('documento')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow( $form->get('descricao')); 
    echo $this->formRow($form->get('email'));?>
</div>

<div class="form-group">
    <?php echo $this->formRow( $form->get('ddd1')); 
    echo $this->formRow($form->get('telefone1'));?>
</div>

<div class="form-group">
    <?php echo $this->formRow( $form->get('ddd2')); 
    echo $this->formRow($form->get('telefone2'));?>
</div>

<h3>Endereço <small>(Necessário quando houver frete)</small> </h3>
<div class="form-group">
    <?php echo $this->formRow($form->get('logradouro'));
    echo $this->formRow($form->get('numero'));
    echo $this->formRow($form->get('complemento'));?>
</div>
<div class="form-group ">
    <?php echo $this->formRow($form->get('bairro'));
    echo $this->formRow($form->get('cidade'));
    echo $this->formRow($form->get('uf'));
    ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('cep')); ?>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->formRow($form->get('submit')); ?>
    </div>
</div>
    
    
    <?php
//echo $this->formRow($form->get('email'));
//echo $this->formCollection($form);
echo $this->form()->closeTag();

?>
