<?php

$title = 'Novo Produto';
$this->headTitle($title);

?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
     
<?php

$this->formElementErrors()
        ->setMessageOpenFormat('<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert">x</button>')
        ->setMessageCloseString('</div>')
        ->Render($form);

$form->setAttribute('action', $this->url('produto/default', array('controller'=>'index','action' => 'insert')));
$form->prepare();

echo $this->form()->openTag($form);
?>


<div class="form-group">
    <?php echo $this->formRow( $form->get('descricao')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('valor'));?>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->formRow($form->get('submit')); ?>
    </div>
</div>
    
    
    <?php
//echo $this->formRow($form->get('email'));
//echo $this->formCollection($form);
echo $this->form()->closeTag();

?>
